import Link from "next/link";
import type { PortfolioItem, Profile } from "@/types";
import PortfolioGallery from "./PortfolioGallery";
import ProfileAvatar from "./ProfileAvatar";

export default function FirmPublicProfile({ profile, portfolioItems, portfolioError, isOwner }: { profile: Profile; portfolioItems: PortfolioItem[]; portfolioError: Error | null; isOwner: boolean }) {
    return (
        <div className="min-h-screen bg-paper text-ink font-sans selection:bg-redline selection:text-paper">
            <main className="mx-auto w-full max-w-7xl px-5 py-8 sm:px-8 sm:py-14">
                <div className="mb-8 flex items-center justify-between font-mono text-[10px] uppercase tracking-[0.2em] text-graphite"><span>Organisation profile / {profile.location ?? "Practice"}</span>{isOwner && <div className="flex gap-4"><Link href="/profile/edit" className="text-redline hover:text-ink">Edit profile ↗</Link><Link href="/settings" className="hover:text-ink">Settings ↗</Link></div>}</div>
                <section className="relative overflow-hidden rounded-[28px] border border-line bg-warm-white p-6 text-ink sm:p-10 lg:p-14">
                    <div className="absolute -right-20 -top-28 h-80 w-80 rounded-full border border-redline/30" /><div className="absolute right-28 top-20 h-28 w-28 rotate-45 border border-ink/15" />
                    <div className="relative grid gap-10 lg:grid-cols-[1.4fr_0.6fr] lg:items-end">
                        <div><p className="eyebrow font-mono text-redline">STUDIO / COMPANY</p><h1 className="display-balance mt-5 max-w-4xl font-display text-6xl font-black leading-[0.82] tracking-[-0.08em] sm:text-8xl">{profile.name}</h1><p className="mt-6 max-w-2xl text-base leading-relaxed text-graphite">{profile.bio ?? "A practice building meaningful work and looking for the people who can help bring it to life."}</p></div>
                        <div className="flex items-end justify-start gap-4 lg:justify-end"><ProfileAvatar profile={profile} size={112} className="h-24 w-24 rounded-2xl border border-line object-cover sm:h-28 sm:w-28" fallbackClassName="bg-paper" /><span className="font-mono text-[10px] uppercase tracking-widest text-graphite">{profile.location ?? "Remote / Nigeria"}</span></div>
                    </div>
                </section>

                <div className="grid gap-5 py-5 lg:grid-cols-[0.7fr_1.3fr]">
                    <section className="rounded-[24px] border border-line bg-warm-white p-6 sm:p-8"><p className="eyebrow font-mono text-redline">WORK WITH US</p><h2 className="mt-4 font-display text-3xl font-semibold leading-[0.95] tracking-[-0.05em]">Looking for the right people?</h2><p className="mt-4 text-sm leading-relaxed text-graphite">Explore current opportunities from studios and companies across the network.</p><Link href="/jobs" className="interactive mt-7 inline-flex rounded-full bg-ink px-5 py-3 font-mono text-[10px] uppercase tracking-widest text-paper hover:bg-redline">See opportunities ↗</Link></section>
                    <section className="rounded-[24px] border border-line bg-warm-white p-6 sm:p-8"><p className="eyebrow font-mono text-redline">CONTACT & CAPABILITY</p><div className="mt-5 grid gap-6 sm:grid-cols-2"><div><p className="font-mono text-[10px] uppercase tracking-widest text-graphite">Based in</p><p className="mt-2 text-sm text-ink">{profile.location ?? "Nigeria"}</p></div><div><p className="font-mono text-[10px] uppercase tracking-widest text-graphite">Find us online</p><div className="mt-2 flex flex-wrap gap-3 font-mono text-[10px] uppercase tracking-widest">{profile.personal_site_url && <a href={profile.personal_site_url} target="_blank" rel="noreferrer" className="text-redline hover:text-ink">Website ↗</a>}{profile.instagram_url && <a href={profile.instagram_url} target="_blank" rel="noreferrer" className="text-redline hover:text-ink">Instagram ↗</a>}{profile.linkedin_url && <a href={profile.linkedin_url} target="_blank" rel="noreferrer" className="text-redline hover:text-ink">LinkedIn ↗</a>}</div></div></div>{profile.software_proficiency.length > 0 && <div className="mt-7 border-t border-line pt-5"><p className="font-mono text-[10px] uppercase tracking-widest text-graphite">Tools & capabilities</p><div className="mt-3 flex flex-wrap gap-2">{profile.software_proficiency.map((tool) => <span key={tool} className="rounded-full border border-line bg-paper px-3 py-1.5 font-mono text-[9px] uppercase tracking-widest text-graphite">{tool}</span>)}</div></div>}</section>
                </div>

                <section className="rounded-[24px] bg-paper p-6 text-ink sm:p-10"><div className="mb-6 flex items-end justify-between gap-4"><div><p className="eyebrow font-mono text-redline">SELECTED WORK</p><h2 className="mt-3 font-display text-3xl font-semibold tracking-[-0.04em]">What we make</h2></div><span className="font-mono text-[10px] uppercase tracking-widest text-graphite">{portfolioItems.length} projects</span></div>{portfolioError ? <div className="border border-dashed border-redline p-8 text-center font-mono text-xs uppercase tracking-widest text-redline">Unable to load work right now.</div> : portfolioItems.length > 0 ? <div className="grid gap-4 md:grid-cols-2">{portfolioItems.map((item) => <article key={item.id} className="overflow-hidden rounded-2xl border border-line bg-warm-white"><PortfolioGallery images={item.images} title={item.title} /><div className="p-5"><p className="font-mono text-[9px] uppercase tracking-widest text-redline">{item.project_type} {item.year ? `// ${item.year}` : ""}</p><h3 className="mt-2 font-display text-xl font-semibold">{item.title}</h3>{item.description && <p className="mt-2 text-sm leading-relaxed text-graphite">{item.description}</p>}</div></article>)}</div> : <div className="border border-dashed border-line p-8 text-center text-sm text-graphite">This practice has not added selected work yet.</div>}</section>
            </main>
        </div>
    );
}
